# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b95e1e05e8fbc388d59aee17d50fc65bbc8ac56380d31b8343e57777c2e1930bfaca68d11044842f20c9f8d343e8f84c366dfd61b1a76ebf27ad899fb312156

test:
  secret_key_base: 6cebb0a67cb0385ed20cccc0eb20cdd1e0b8150242a61967b6f2edf2f752bd3a9fbaff961efec8d1be5acd2b82129c6c50ad25971f440dde14382b66bdf3406b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
